"""
Gait control bytes
"""

ACTION_NONE = 0
ACTION_FORWARD = 1
ACTION_BACKWARD = 2
ACTION_UP = 3
ACTION_DOWN = 4
ACTION_HOME = 5

GAIT_FORWARD = 0
GAIT_BACKWARD = 1
GAIT_TURN_LEFT = 2
GAIT_TURN_RIGHT = 3

GAIT_HOME = 5

# RECENTER = 4 
# WIGGLE = 5

gaits = {
    GAIT_FORWARD: [
        (ACTION_NONE, ACTION_UP, ACTION_NONE, ACTION_UP, ACTION_NONE, ACTION_UP),
        (ACTION_NONE, ACTION_FORWARD, ACTION_NONE, ACTION_FORWARD, ACTION_NONE, ACTION_FORWARD),
        (ACTION_NONE, ACTION_DOWN, ACTION_NONE, ACTION_DOWN, ACTION_NONE, ACTION_DOWN),
        (ACTION_UP, ACTION_NONE, ACTION_UP, ACTION_NONE, ACTION_UP, ACTION_NONE),
        (ACTION_NONE, ACTION_BACKWARD, ACTION_NONE, ACTION_DOWN, ACTION_NONE, ACTION_DOWN),
        (ACTION_DOWN, ACTION_NONE, ACTION_DOWN, ACTION_NONE, ACTION_DOWN, ACTION_NONE),
    ],
    GAIT_BACKWARD: [
        (ACTION_BACKWARD, ACTION_UP, ACTION_NONE, ACTION_UP, ACTION_NONE, ACTION_UP),
        (ACTION_BACKWARD, ACTION_UP, ACTION_NONE, ACTION_UP, ACTION_NONE, ACTION_UP),
    ],
    GAIT_TURN_LEFT: [
        (ACTION_FORWARD, ACTION_UP, ACTION_NONE, ACTION_UP, ACTION_NONE, ACTION_UP),
        (ACTION_FORWARD, ACTION_UP, ACTION_NONE, ACTION_UP, ACTION_NONE, ACTION_UP),
    ],
    GAIT_TURN_RIGHT: [
        (ACTION_UP, ACTION_UP, ACTION_NONE, ACTION_UP, ACTION_NONE, ACTION_UP),
        (ACTION_UP, ACTION_UP, ACTION_NONE, ACTION_UP, ACTION_NONE, ACTION_UP),
    ],
    GAIT_HOME: [
        (ACTION_HOME, ACTION_HOME, ACTION_HOME, ACTION_HOME, ACTION_HOME, ACTION_HOME), 
    ]
    
    # WIGGLE: [
    #     (ACTION_FORWARD, ACTION_NONE, ACTION_FORWARD, ACTION_NONE, ACTION_FORWARD, ACTION_NONE)
    #     (ACTION_FORWARD, ACTION_NONE, ACTION_FORWARD, ACTION_NONE, ACTION_FORWARD, ACTION_NONE)
    # ],
    
    # RECENTER:[
    #     (ACTION_HOME, ACTION_HOME, ACTION_HOME, ACTION_HOME, ACTION_HOME, ACTION_HOME)   
    # ]
}