"""
Gait control bytes
"""

# ACTIONS (forward/backward mean hip movement, up/down mean knee movement)
ACTION_NONE = 0
ACTION_FORWARD = 1
ACTION_BACKWARD = 2
ACTION_UP = 3
ACTION_DOWN = 4
ACTION_HOME = 5

# GAITS
GAIT_FORWARD = 0
GAIT_BACKWARD = 1
GAIT_TURN_LEFT = 2
GAIT_TURN_RIGHT = 3
GAIT_HOME = 5

# divide each cycle into 10 steps
# tripod gait - steps separated by 1/2 period, which means 5 steps each
# stance phase - grounded legs move hip motors backwards
# lifting and lowering - no hip motor movement

gaits = {
    GAIT_FORWARD: [
        #### GROUP 1 LEGS 1, 3, 5 ####
        # up
        (ACTION_UP, ACTION_NONE, ACTION_UP, ACTION_NONE, ACTION_UP, ACTION_NONE),
        
        # swing phase - leg in air, grounded legs move back
        (ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD),
        (ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD),
        
        # down
        (ACTION_DOWN, ACTION_NONE, ACTION_DOWN, ACTION_NONE, ACTION_DOWN, ACTION_NONE),
        
        # return to neutral stance phace
        (ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD),
        (ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD),
        
        #### GROUP 2 LEGS 2, 4, 6 ####
        # up
        (ACTION_NONE, ACTION_UP, ACTION_NONE, ACTION_UP, ACTION_NONE, ACTION_UP),
        
        # swing phase
        (ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD),
        (ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD),
        
        # down
        (ACTION_NONE, ACTION_DOWN, ACTION_NONE, ACTION_DOWN, ACTION_NONE, ACTION_DOWN),
        
        # return to neutral stance phase
        (ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD),
        (ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD),

    ],
    
    # reverse of fwd
    GAIT_BACKWARD: [
        #### GROUP 1 LEGS 1, 3, 5 ####
        # up
        (ACTION_UP, ACTION_NONE, ACTION_UP, ACTION_NONE, ACTION_UP, ACTION_NONE),
        
        # swing phase - leg in air, grounded legs move back
        (ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD),
        (ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD),
        
        # down
        (ACTION_DOWN, ACTION_NONE, ACTION_DOWN, ACTION_NONE, ACTION_DOWN, ACTION_NONE),
        
        # return to neutral stance phace
        (ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD),
        (ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD),
        
        #### GROUP 2 LEGS 2, 4, 6 ####
        # up
        (ACTION_NONE, ACTION_UP, ACTION_NONE, ACTION_UP, ACTION_NONE, ACTION_UP),
        
        # swing phase
        (ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD),
        (ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD),
        
        # down
        (ACTION_NONE, ACTION_DOWN, ACTION_NONE, ACTION_DOWN, ACTION_NONE, ACTION_DOWN),
        
        # return to neutral stance phase
        (ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD),
        (ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD, ACTION_BACKWARD, ACTION_FORWARD),
    ],
    
    GAIT_TURN_LEFT: [
        (ACTION_FORWARD, ACTION_UP, ACTION_NONE, ACTION_UP, ACTION_NONE, ACTION_UP),
        (ACTION_FORWARD, ACTION_UP, ACTION_NONE, ACTION_UP, ACTION_NONE, ACTION_UP),
    ],
    GAIT_TURN_RIGHT: [
        (ACTION_UP, ACTION_UP, ACTION_NONE, ACTION_UP, ACTION_NONE, ACTION_UP),
        (ACTION_UP, ACTION_UP, ACTION_NONE, ACTION_UP, ACTION_NONE, ACTION_UP),
    ],
    
    GAIT_HOME: [
        # home 3 legs at a time to prevent instability
        (ACTION_HOME, ACTION_NONE, ACTION_HOME, ACTION_NONE, ACTION_HOME, ACTION_NONE), 
        (ACTION_NONE, ACTION_HOME, ACTION_NONE, ACTION_HOME, ACTION_NONE, ACTION_HOME), 
    ]
    
    # WIGGLE: [
    #     (ACTION_FORWARD, ACTION_NONE, ACTION_FORWARD, ACTION_NONE, ACTION_FORWARD, ACTION_NONE)
    #     (ACTION_FORWARD, ACTION_NONE, ACTION_FORWARD, ACTION_NONE, ACTION_FORWARD, ACTION_NONE)
    # ],
    
}